language: node_js
node_js:
- '6'
- '5'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: TU28DzhBqMSntn6ioBti9SKDpNt6cEbqTVqiZbKx6+6sKQe9USR+pbqQEqa7/2zY+J+sQ40zhNFaUrypds6Rp39FhVYgnW1l5QfjSdfeIE0PUiAeiBOW8+0qc7KstT/d98WmqTOi3eiV69x1cKQ777RvXakl6QzMnkF8zJV08Alo/1nDzodk40v6qAKHhtoPP8DwgdR60kSKpFd/y3B5TImjAbt9eLOVMzvcjKizM005iOCqUVGLUQ+Ooee62OQkqgANFMYrzT8NGTTsO2VmlcCi+rJl5qMVzLPQHwtVVUv9ocuFCF4DIhQvEtm/BDTyrrKUMiNamzGOUCbIfHbRQQqhFVWVXZ4YQ+y8/CbYw6xHs8wPgv4KD8D2r5QuLPXQ1Zu6v7krW0YmXy6pgq4d6DIHL/90yozV6slEvSDs93m8DBzh9/M4cBj8EUEHEfVfJy4G6ITF+bKpPl3DLKkKNKOK6tBZyVVez3bmMqqR3CjZl0zPavqExCtS2yd6AQlVq9sNwkEOQWTdd7qcuMC6c2g+VDlkywrUrRHyPaQ9WUcNnhubODU296V+QwSougSgo6/fTvthYaN5d4iZQqkwXf+2oEKBM5RMtFstmb16gQfEqy5MVvhsJtl6QirHXpBSTfWzFeSXUvq24MutmxqoaOAjg+akN8TRj6E5LD2iYxg=
  - secure: ZbKDOb9JJaVMKhXPxWTE8OhMzwZEvxosVkbfQO5GGvOD6lq5umjcy/LnRRLU5EMVoq+avCUhcB3ZJybiHaQVe5FIUW2x/HOxome5srz2nEDmnKiUy5qbXZlj8VS3VIabNVaiHl79w9V8NuDZ5ok+9h2GWTcSOEtb3JsL4xghSmx/fae3pNn0oSMmpPm8qfEDnjE3qN74rQmReMVpQJUiKric2Cmfq/fW2kk//N1rcImihplQ8owqdQcBEZr8e3/SWEfXy5hQ1scUDtkJ1/im3K4u0bZ2SaZqaDwsiUQZBOHYUFdIj95vzP6hpssT8toWPBsnRv+ZOJLQcSb8LhEDwzww72Z+kZoUjyOERtj5pMOAu09pOwH7JU/1GqKi5GLuHgQAmuqMth3NvBEgGwglDFyOubRuzIwCHQ0Z3NbO1Bte+nYwEIG/A185lPItNDNBYLzUQ7DT/JvcomO/skBMZ2P3bTLU/mkoDbTzDCxMjlmFYNErUj38qoZGID9NCIWZRNKzHWtVJhOIF/RWj2aU+CHdgdDDQK43sKrG0U8bnvEB6a8mhO2yLfBnI0l2YRSTrR3e+CTZcAvS9/w1HkXw4v5NjCOPXJr2YwB4mBnQ1QbdI9IYkEoqmzX6WF+CNu0NgPNsK0yfI6HnXmARJ/nFODuejKEEwt/7GBBpZuonvB4=
addons:
  sauce_connect: true
